SELECT
    A.APNT_NO,
    P.PT_NAME,
    A.PT_NO,
    A.MCDP_CD,
    D.DR_NAME,
    A.APNT_YMD
FROM
    APPOINTMENT A
JOIN
    PATIENT P
    ON A.PT_NO = P.PT_NO
JOIN
    DOCTOR D
    ON A.MDDR_ID = D.DR_ID
WHERE
    YEAR(A.APNT_YMD) = 2022
    AND
    MONTH(A.APNT_YMD) = 4
    AND
    DAY(A.APNT_YMD) = 13
    AND
    A.APNT_CNCL_YN = 'N'
    AND
    A.MCDP_CD = 'CS'
ORDER BY
    6;